<?php
namespace ProcessWire;
/** @var Config $config */
/** @var Wire $wire */
/** @var Page $page */
/** @var Pages $pages */

/**
 * ProcessWire Configuration File
 *
 * Site-specific configuration for ProcessWire.
 * This config.php file was generated by the ProcessExportProfile module.
 *
 * Please see the file /wire/config.php which contains all configuration options you may
 * specify here. Simply copy any of the configuration options from that file and paste
 * them into this file in order to modify them.
 *
 * ProcessWire 2.x
 * Copyright (C) 2014 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://processwire.com
 *
 */

if(!defined("PROCESSWIRE")) die();

/*** SITE CONFIG *************************************************************************/

/**
 * Enable debug mode?
 *
 * Debug mode causes additional info to appear for use during dev and debugging.
 * This is almost always recommended for sites in development. However, you should
 * always have this disabled for live/production sites.
 *
 * @var bool
 *
 */
$config->debug = false;



/*** INSTALLER CONFIG ********************************************************************/

setlocale(LC_ALL, "en_US.utf8");

/**
 * Installer: Database Configuration
 *
 */
$host = $_SERVER['HTTP_HOST'];
$local = [
	'localhost:8080',
	'localhost',
	'localhost:80',
	'localhost:8888',
	'192.168.0.175:8080',
	'dev.xtoolslist.phz',
	'xtoolslist.tk',
	'207.148.19.180'
];
$config->dbHost = 'localhost';
$config->dbPort = '3306';
if(in_array($host,$local)) {
	$config->dbName = 'xtoolslist';
	$config->dbUser = 'xtools';
	$config->dbPass = 'jg21c_8T';
	if($host === "localhost:8888") { // Mac MAMP
		$config->dbPass = 'root';
	}
}
else {
	$config->dbName = '';
	$config->dbUser = '';
	$config->dbPass = '';
}

/**
 * Installer: User Authentication Salt
 *
 * Must be retained if you migrate your site from one server to another
 *
 */
$config->userAuthSalt = '5892ad84b349994de9e76e76addf408d';

/**
 * Installer: File Permission Configuration
 *
 */
$config->chmodDir = '0755'; // permission for directories created by ProcessWire
$config->chmodFile = '0644'; // permission for files created by ProcessWire

/**
 * Installer: Time zone setting
 *
 */
$config->timezone = 'Asia/Manila';

/**
 * Installer: Unix timestamp of date/time installed
 *
 * This is used to detect which when certain behaviors must be backwards compatible.
 * Please leave this value as-is.
 *
 */
$config->installed = 1482027154;

/**
 * Installer: HTTP Hosts Whitelist
 *
 */
$config->httpHosts = array(
	'localhost:8080',
	'localhost',
	'localhost:80',
	'localhost:8888',
	'192.168.0.175',
	'192.168.0.175:8080',
	'118.127.43.111',
	'116.90.60.131',
	'dev.xtoolslist.phz',
	'207.148.19.180',
	'xtoolslist.tk'
);
setlocale( LC_ALL, "en_US.utf8" );
$config->advanced = true;
$config->defaultAdminTheme = 'AdminThemeUikit';

//global Walk Creative CMS autoload class function
spl_autoload_register(function ($class_name_in) {
	global $config;
	$classParts = explode("\\", $class_name_in);
	$class_name = $classParts[count($classParts) - 1];
	if(file_exists($config->paths->templates . 'core/' . $class_name . '.php')) {
		include_once $config->paths->templates . 'core/' . $class_name . '.php';
	}
});
